Task:
    type: object
    config:
        fields:
            id:
                type: "ID!"
            title:
                type: "String!"
                resolve: "@=value.getTitle()"
            description:
                type: "String!"
                resolve: "@=value.getDescription()"
            status:
                type: "TaskStatus!"
                resolve: "@=value.getStatus().value"
            assignedUser:
                type: "User!"
                resolve: "@=value.getAssignedUser()"
